Reword zoom
StepUp-Tutoring/firebase-code pull request #102
Opened 2021-10-07 05:18 UTC by XueyangSong

<img width="1069" alt="Screen Shot 2021-10-06 at 22 18 09" src="https://user-images.githubusercontent.com/49179682/136324340-14368adf-6f36-4f93-919e-37af5ebfb4c1.png">

Screenshot attached.

2021-10-07 20:32 UTC, naclcaleb commented on public/src/TutorHome.js
> +                            This Zoom link is your dedicated Zoom link with
The wording here is a little repetitive, so I would change it to "This is your dedicated Zoom link..." rather than "This Zoom link is your dedicated Zoom link."

2021-10-07 20:33 UTC, naclcaleb commented on public/src/TutorHome.js
> +                            This Zoom link is your dedicated Zoom link with
The wording here is a little repetitive - I would change it to "This is your dedicated Zoom link with..." rather than "This Zoom link is your dedicated Zoom link..."

2021-10-07 20:35 UTC, naclcaleb commented on public/src/TutorHome.js
> +                        <div style={{ position: 'relative', width: '70%', height: 40 }}>
I think it would look nicer if we had a label _above_ the gray box that just says "Meeting ID:", and then just had the number in the gray box with a "Copy" button exactly like the one above.

The label and gray box will also need some extra margin so things look neat and tidy.

2021-10-08 07:03 UTC, XueyangSong commented on public/src/TutorHome.js
> +                        <div style={{ position: 'relative', width: '70%', height: 40 }}>
<img width="1202" alt="Screen Shot 2021-10-08 at 00 02 55" src="https://user-images.githubusercontent.com/49179682/136512746-d0be5760-54c0-414a-ad8d-546dc3d89602.png">

2021-10-08 17:57 UTC, naclcaleb requested changes

2021-10-08 17:57 UTC, naclcaleb commented on public/src/TutorHome.js
> -
It looks good, but we still want to have the other (original) gray box above it with the link, so the order will be:
- Description
- Start Meeting button
- Label saying “Meeting Link”
- Gray box with copyable link
- Label saying “Meeting ID”
- Gray box with copyable meeting ID

2021-10-08 18:33 UTC, XueyangSong commented on public/src/TutorHome.js
> -
<img width="969" alt="Screen Shot 2021-10-08 at 11 33 01" src="https://user-images.githubusercontent.com/49179682/136608977-b703bbe5-981b-4022-977c-3cc0be96e82b.png">

2021-10-08 21:05 UTC, XueyangSong commented on public/src/TutorHome.js
> -
<img width="908" alt="Screen Shot 2021-10-08 at 14 05 14" src="https://user-images.githubusercontent.com/49179682/136624690-d3b94e66-af84-4326-8516-412f2ce58443.png">

2021-10-08 21:11 UTC, naclcaleb approved these changes

2021-10-08 21:11 UTC, naclcaleb commented on public/src/TutorHome.js
> -
Looks good; I'll handle the merge conflict

2021-10-08 21:29 UTC, merged